// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@v0.22.0',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowMinimal(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/minimal/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-spring-boot-jkube-jenkins-min',
    workflowServiceAccountName: 'ploigos-workflow-ref-spring-boot-jkube-jenkins-min',

    workflowWorkerImageDefault: 'ploigos/ploigos-base:v0.22.0',
    workflowWorkerImageAgent: 'ploigos/ploigos-ci-agent-jenkins:v0.22.0',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:v0.22.0',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-jkube:v0.22.0',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:v0.22.0',

    stepRunnerUpdateLibrary: true,
    stepRunnerLibSourceUrl: 'git+https://github.com/itewk/ploigos-step-runner.git@feature/container-image-digests'
)
