// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@main',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowMinimal(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/minimal/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-spring-boot-jkube-jenkins-min',
    workflowServiceAccountName: 'ploigos-workflow-ref-spring-boot-jkube-jenkins-min',

    workflowWorkerImageDefault: 'ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImageAgent: 'ploigos/ploigos-ci-agent-jenkins:nightly',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-jkube:nightly',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:nightly'
    stepRunnerUpdateLibrary: 'true',
    stepRunnerLibSourceUrl: 'git+https://github.com/ploigos/ploigos-step-runner.git@main',

)
