---
step-runner-config:
  global-defaults:
    application-name: ref-spring-jkube-jenkins-typ

  deploy:
  - implementer: ArgoCD
    config:
      deployment-config-repo: http://gitea.tssc.rht-set.com/ploigos-reference-applications/reference-sprint-boot-mvn-jkube-cloud-resources_jenkins_workflow-typical.git
