---
step-runner-config:
  config-decryptors:
  - implementer: SOPS

  global-defaults:
    organization: ploigos-ref
    service-name: hello

    maven-servers:
      nexus.apps.tssc.rht.set.com:
        id: nexus.apps.tssc.rht.set.com
        username: sa-ploigos-ref-apps
    maven-mirrors:
      nexus.apps.tssc.rht.set.com:
        id: nexus.apps.tssc.rht.set.com
        url: https://nexus.apps.tssc.rht-set.com/repository/maven-public/
        mirror-of: '*'
    container-registries:
        registry.redhat.io:
            username: 6340056|tssc-integration-infra
        registry-internal-nexus.apps.tssc.rht-set.com:
            username: sa-ploigos-ref-apps

  generate-metadata:
  - implementer: Maven
  - implementer: Git
  - implementer: SemanticVersion

  package:
  - implementer: MavenPackage

  create-container-image:
  - implementer: MavenJKubeK8sBuild
    config:
      maven-profiles:
      - kubernetes

  push-container-image:
  - implementer: Skopeo
    config:
      destination-url: registry-internal-nexus.apps.tssc.rht-set.com

  deploy:
  - implementer: ArgoCD
    config:
      argocd-api: argocd-server-argocd.apps.tssc.rht-set.com
      argocd-username: admin
      argocd-skip-tls: True
      deployment-config-helm-chart-path: charts/reference-spring-boot-mvn-jkube-deploy
      deployment-config-helm-chart-values-file-image-tag-yq-path: 'image.tag'
      git-username: sa-ploigos-ref-apps
      git-email: 'napsspo+tssc@redhat.com'
      argocd-sync-timeout-seconds: 130
    environment-config:
      DEV:
        deployment-config-helm-chart-environment-values-file: values-DEV.yaml
      TEST:
        deployment-config-helm-chart-environment-values-file: values-TEST.yaml
      PROD:
        deployment-config-helm-chart-environment-values-file: values-PROD.yaml

  report:
  - implementer: ResultArtifactsArchive
    config:
      results-archive-destination-url: https://nexus.apps.tssc.rht-set.com/repository/release-engineering-workflow-result-artifacts-archives/
      results-archive-destination-username: sa-ploigos-ref-apps
