// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@feature/params-refactor',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/itewk/ploigos-jenkins-library.git'
])

// run the pipeline
jkube11ServicePloigosWorkflowTypical(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/typical/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-spring-boot-jkube-jenkins-typ',
    workflowServiceAccountName: 'ploigos-workflow-ref-spring-boot-jkube-jenkins-typ'
)
