// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@main',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowTypical(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/typical/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-spring-boot-jkube-jenkins-typ',
    workflowServiceAccountName: 'ploigos-workflow-ref-spring-boot-jkube-jenkins-typ',

    workflowWorkerImageDefault: 'ploigos/ploigos-base:pr-95',
    workflowWorkerImageAgent: 'ploigos/ploigos-ci-agent-jenkins:pr-95',
    workflowWorkerImageUnitTest: 'ploigos/ploigos-tool-maven:pr-95',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:pr-95',
    workflowWorkerImageStaticCodeAnalysis: 'ploigos/ploigos-tool-sonar:pr-95',
    workflowWorkerImagePushArtifacts: 'ploigos/ploigos-tool-maven:pr-95',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-jkube:pr-95',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'ploigos/ploigos-tool-openscap:pr-95',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:pr-95',
    workflowWorkerImageUAT: 'ploigos/ploigos-tool-maven:pr-95'
)
