// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@feature/debug',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/itewk/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowTypical(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/typical/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-spring-boot-jkube-typ-hello',
    workflowServiceAccountName: 'ploigos-workflow-ref-spring-boot-jkube-typ-hello',

    workflowWorkerImageDefault: 'ploigos/ploigos-base:v0.20.0',
    workflowWorkerImageAgent: 'ploigos/ploigos-ci-agent-jenkins:v0.20.0',
    workflowWorkerImageUnitTest: 'ploigos/ploigos-tool-maven:v0.20.0',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:v0.20.0',
    workflowWorkerImageStaticCodeAnalysis: 'ploigos/ploigos-tool-sonar:v0.20.0',
    workflowWorkerImagePushArtifacts: 'ploigos/ploigos-tool-maven:v0.20.0',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-jkube:v0.20.0',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'ploigos/ploigos-tool-openscap:v0.20.0',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:v0.20.0',
    workflowWorkerImageUAT: 'ploigos/ploigos-tool-maven:v0.20.0',

    workflowWorkersImagePullPolicy: 'IfNotPresent',
    stepRunnerUpdateLibrary: true,
    stepRunnerLibSourceUrl: 'git+https://github.com/itewk/ploigos-step-runner.git@feature/jkube'
)
